# Generated by Django 2.2 on 2020-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=128, unique=True)),
                ('info', models.CharField(max_length=256)),
                ('platform', models.CharField(choices=[('SGE', 'SGE'), ('local', 'local')], default='SGE', max_length=32)),
                ('cores', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('outpath', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
    ]
