# Generated by Django 2.2 on 2020-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wes',
            name='user',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
