# Generated by Django 2.2 on 2020-09-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patiantinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatiantReportTable',
            fields=[
                ('项目编号', models.AutoField(primary_key=True, serialize=False)),
                ('报告', models.FileField(blank=True, null=True, upload_to='Reports/Company/%Y-%m-%d', verbose_name='报告')),
                ('Patiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patiantinfo.PatiantInfo')),
            ],
        ),
    ]
